export const SET_RECORDING_PROTECTION = 'SET_RECORDING_PROTECTION';
export const SET_RECORDING_PROTECTION_REQUEST = 'SET_RECORDING_PROTECTION_REQUEST';
export const SET_RECORDING_PROTECTION_PENDING = 'SET_RECORDING_PROTECTION_PENDING';
